### ISSUE TITLE
data-N properties are too generic and don't have a namespace

### ISSUE THREAD

**Issue by OscarGodson** [LeaVerou/animatable#30]
This is an awesome script, but the `data-property`/`to`/`from` properties are too generic and there's no namespace to keep it from clobbering some other script that might end up using the generic "`property`" word down the road. What if it were like:

``` html
<div data-animatable-property="n" data-animatable-to="x" data-animatable-from="y"></div>
```

Just a suggestion for implementing into larger apps, and it's not hard change on my end but something so simple and awesome I presume will be used by designers going "WTF Y IT NO WORK?!" :)

**Comment by LeaVerou** [comment]
It's not a library meant to be used in other projects, it's just a gallery to demonstrate how different animatable properties look when animated. It wasn't written to work in any other project. I only wrote the script to avoid typing repetitive code. It never even crossed my mind that someone might want to use the same script in a project, why would they do that? 
For one, it would mix presentation and behavior. The animation _is_ the content in this case, so it's not mixing them, but in any other project it would. And probably a shitload of other issues, as it wasn't written with that in mind.

**Comment by a3lypheboss** [comment]
My 2 Cents on it (because i think this is a nice code-project which CAN BE a pure plus to A LIBRARY)...

I told my opinions for using HTML 5 strictly in my answer on Leas closing of my pull-request ('just hyped ...') which was just a request for discussion purposes; By strictly using HTML 5 i think of making a readable difference between XHTML and HTML, which has many simple reasons, one of them you mentioned here slightly Oscar:

data-N properties are too generic and don't have a namespace you told;

Let me fuzz on it: data-N properties ARE GENERIC - TRUE, BUT if you let your docs parse as HTML 5 by using <!DOCTYPE HTML> any browser who has no knowledge of HTML 5 can render perfectly in HTML. And there is no existing browser that don't do that in such a case. So it is NOT TOO GENERIC.

... they don't have a namespace you told: TRUE - Fortunately! Because namespaces are a concept that is biting with the concept of HTML; if we would talk about XHTML,XML, etc. i would totally agree with you, but in this case not; Take SVG and MATH-ML for example - maybe you want to read some about namespaces in relation to these two and how they find their way into HTML 5 and what a big problem it was, because HTML IS A COLLECTION OF STRUCTURES - XHTML instead IS A NORMATIVE OF STRUCTURES. By the way: How do you (want to) use namespaces with HTML 5?

A solution to the 'problem' you stated here may be the following:

Correct usage of dataAttributePropertyAutomagicallyPutInCamelCaseDueToTheFactDocWasRenderedAsHtml5 ...
Or to be a bit more precise: the data-N-Properties like you call them have their own API for manipulation through ECMA-Script inside the DOM. The way used actually is a mix of classic DOM-manipulation for HTML as used in DHTML with a touch of classy ActionScript minified-XML-Request for getting html-nodes and virtual-attributes. The way actually used is perfect for downwards compatibility for browsers who allow DOM-manipulation but are not able to manage DOM-dataAttributes.

I hope i have given you two and possibly other readers another perspective on that matter.

If you are interested in modifying the scripts according to that i would gladly be part of the team.

Thank you.

Claudius Raphael Paeth, A3lyphe
every breaking atom living ...

**Comment by OscarGodson** [comment]
I don't think you understand my concern. This was just a demo, but if it wasn't, I was trying to say that it's good practice to put a namespace on data-N properties like data-mylibrary-property so that, with any library, they don't have conflicts. I'm a JavaScript guy, so I know about the HTML5 data API, i was saying, so when you do go to use it, two libraries using `data-property` don't have conflicts. I'm actually a little confused at what you were trying to say...

**Comment by a3lypheboss** [comment]
Well Oscar,
it seems we misunderstood both, but on a second thought we gladly agree without knowing it.

You're right when you say a virtual namespace given by segmentation of the dataProperty-set as if it is part of a namespace is an appropriate way to go.

But: If you already go with naming conventions that share a thought on dependency/property (means that they are human readable as sorted|nested|named parts of a specific instruction set), they should also been taken related to their true identity, or not?

Due to the fact we have no true namespaces in any kind of HtML-based DOM-adaptation there should be a clean consensus about HOW TO HANDLE NAMES.

See, we have many kind of naming-abilities, especially when we took the actual set of languages, their objects, elements, selectors, properties and events; but just a few naming-conventions are subtile on the one and useful on the other hand.

The one and only proper naming would be CamelCase, but even in that simple variant are many differences about how people understand the why and when of its usage.

Exam: You are a JavaScript-Coder who is able to build phenomenal structures with fantastic interfaces and anything you write is a pure functional module, that could easily be left or added to whatever. But then you want to share your perfection with others, because you have no experience in using style-sheets and the dom-style-object is such a shame for its rendering speed in comparison to the CSS-renderer. And also you want to collect your old perfect style-manipulation-sets according to special elements and collections of elements, but whatever cache-technique you use you won't get to such lightning-fast element-collections as given via the CSS-Selectors by just adding a touch of class. If you know what i mean ...

You don't?

Then you might have found a fantastic solution to cache iterations of real-time-modified node-sets, so that they can be collected more quick than the browser does via selectors. Hmm, sorry that i don't believe that.

So, what most people don't think about is, that it is NOT the strict segmentation of documents and not the strict splitting of scripts, styles and structures.

The real benefit is a naming and sorting convention when you respect the way the data flows.

So to get back to your saying: It is not a benefit if you just give anything you did (if did well or not so, doesn't matter) your own name.

So a 

<P data-myfirm-myappname-mydevname-myversion-myattributename="myvalueThatIsntInterestingAnymore anothervalueIputInBecauseImToLazytoSortThingsout">

is not a true contestor to a

<P
 data-sets=mySet
 data-keys=perfection
 data-values=perfect


or even better

<HR
 data-sets=mySetName|mySetItem1|mySetItem2
 data-mySetItem1=myValue
>

or whatever you do think of ...

if you don't get what i mean, let's take it to the styles

Normally you use stylesheet-classes for ... uhem, yeah for what do YOU use them? Because there is no rule for what to use them they are used for anything. Good? No! Bad! Really, really bad. Why? Because creativity is born by breaking barriers by bowing NOT breaking rules.

And you? I repeat my question: For what do YOU use stylesheet-classes? Let's say you have experienced a lot in coding and now after years and years of probing und fuddling with any kind of browser you say you just use classes for styles, but hey now we have query-selectors and before that we had Sizzle, jQuery, etc. and before that we already had the DOM again and even if not implemented we had Quasi-DOM, or we had XPath or we had ...

Come on, do you really don't get it?

We have had so much to learn and to try with guaranteed errors, you can't say you don't know what i am talking about.

What are stylesheet-classes for?

Why can stylesheet-classes be nested, bundled and appended by pseudo-elements?

Oscar, i've written a lot. It is enough for now.

Instead of a clear answer to your question i give you a task:

Name three well-known web-applications that use stylesheet-classes for their graphical representation in the exact same way they use nested overloaded-functions for the rendering of the content and before that, the generation of the necessary structure.

Let me guess, you're answer will link to some fancy stuff like php, ruby, yaml, asp, jsp, json or whatever buzzword comes into sense;

The right answer to all given questions is easy: Use structure for what it is: as a fundamental where any possible future building instructions are pinnened to in the right place. Use class, id and name extensively as necessary to let the code explain itself and to give the dom the opportunity to let your scripts deliver and let them know when and how.

If you think there is anything inside my note, that remembers you of what you are really able to do with the most magnificent language-set, that we discuss here: HtML CSS JS -- then please let us talk about specifics.

This goes out to all of you; It is time to rethink, not to reconstruct.

every breaking atom living ???

Claudius Raphael Paeth, A3lyphe

**Comment by OscarGodson** [comment]
Im sorry, but i have no clue what you're talking about. I'm not even talking about CSS at all just that a namespace would be nice, not even really suggesting how, just you should. But, this isn't a real library anyways so it's irrelevant. Also, I think a bunch of your code is missing. Maybe this is another reason Im confused. 

I'm really trying to understand what you're trying to say, and I've read it like 5 times. I don't understand how these things lie "name three well-known web apps..." has anything to do with appending a namespace...

And php, yaml, and esp. asp, jsp  aren't buzzwords. Personally, I haven't heard someone mention JSP in... years.

**Comment by LeaVerou** [comment]
I agree with Oscar, noooo idea either.
Being more brief might help. Nobody has the time to carefully study 500-1000 word long comments.

**Comment by a3lypheboss** [comment]
Hi Oscar, hi Lea,
i've seen there is a bunch of comments on my sayings. I'll try to be briefly going on with any, so starting here.

Fact is:
- Browsers are able to let coders select elements and there nested childs via general mechanisms like id, name and tagname.
- The most used is: document.getElementById(id), 2nd most used is document.getElementsByTagName('TAG')
- any modern library and actual browser deliver a way to collect elements by className

CSS has as already told (and you know them well i think) it's own selectors; the obvious but often not seen (especially by pro's) is that these selectors are just a shorthand form of given DOM selectors.

My problem with pro's and their suggestions to people who don't know yet how to use selectors is that they mostly agree that id's are a guaranteed way to catch single elements, that tagNames are perfect for collections and that names just have guaranteed usability for forms.

And most pro's tell those who don't know it better yet, that if they want to have more options to filter their structure they have to build whatever they think is right and then use a queryselector as given in well-known libraries and modules that perform perfectly when used with XPath or CSS-Selectors.

My intervention was:

Why should anyone use a bunch of javascript that allows me to use shorthand selectors as given by CSS just to identify my not-so-well-discussed-by-myself-in-relation-to-my-needs elements in my structure i have built as a non-pro?

It would be much more useful when (especially guys like you) would rethink on the structure itself and the functions they have to let follow, like:

What is an id? An ID is an identifier that should give ONE element the possibility to be identified for sure via a script that can operate the DOM.

So to get to the point: An ID is itself a NAMESPACE, because an ID is operatable from anywhere you can run your script if it is on purpose, by fixed procedure or by event.

A class-Attribute of an Element contains ONE OR MORE classnames (Stylesheet-Collections) that are assigned to it through that, BUT if more than one classname is assigned to an element in the class-attribute they are themselves an identifier, that like an ID can be uniquely adressed, but can be given more than ONE time (which an ID can't).

So a paragraph with the class-value of myNameSpace can never be a namespace, because a namespace has to be declared once and can not be named twice. 

But what about a #Namespacevendor .my.application.name.space?
.my.application.name.space is in HTML and CSS and JavaScript the same! Even if .my is defined or .application or .name or .space is: It is just an overloaded selector for a specific functional styling (CSS) and/or object (JS) which can be declared on any given element (HTML)

What do we have in the scripts section? We have anonymous functions that can operate as void functions, classes with anonymously called constructors to generate true singletons, we have functions that are declared through variables contained in the window-context and we have functions that do not operate, instead are objects with constructors to be used as classes for immediate|lazy local|global creation of instances. In short, we have the same structures we can build as we are able to produce with pure element-attribute-structuring and callable via styles, controllable via scripts.

The matter of my intervention is that it is not clear to anyone (especially for you both, too, it seems; which let's me wonder) that any script can also be simply made a library by just changing the structure, not the content.

Or do you really see a problem in making a library or a module compatible to given libraries out of your code? i don't think so, when you already use anonymous functions, nested lazy functions, regex matches and argument-capture just to perform what could be simpler and self-explaining (but less stylee and geeky for sure) by just restructuring.

So to resume: I just wanted you both to remember, that there is no need for a discussion about 'is it useful if it would be a library?' Sry: It is already; And no need to shuffle thoughts about the use of namespaces: Use an ID you have a true namespace.

It's such simple that most people forget.

P.s.: Lea you do codework that is truly good on both sides of the medal: you use concepts that show off many different techniques and you use them in an efficient manner AND you try to make them understandable with a lesser amount of documentation just by giving them structure. That's good. But if you want to go a step further and be really good (for yourself and to help others understand), reduce the knowledge level needed where it makes no difference in efficiency, but let your code become stepwise understandable for beginners.
1. Delivering a true namespace - just by spending a nest through a container with an id (maybe you forget that your script-elements can also hold id's :) )
2. Use the fact that elements and its childs can be constructed via DOM-methods AND ALSO can contain properties, because themselves they are objects, which can store the whole bunch of codework needed, which results in a no-dependency on virtual browser-objects like window|global-namespace.
3. Don't forget that you can use DOM-methods in a bunch of languages (PHP,Java, for example) in combination with other graphical-renderers than the browsers deliver (window there is not the same as window here) ...

If you both now afterall have no idea what i mentioned here, then i'm sorry, but maybe other readers might understand it, so possibly it would be nice to let it live, even if it is not the right place.

I am sure this is the right place and you both have the capabilities to spend a proper thinking on it.

P.p.s.: For a beginner in web-developing php, asp, ruby, etc. are buzzwords because they are used very often by professionals where they have no idea how to use clientside ECMA-scripting to perform the same tasks, just because they DO NOT RETHINK.

Personally i think a 500-1000 word long comment or longer is favourable, especially if the comment is fed up with further leading thoughts to the original idea.

I can understand if you aren't interested in longer readings, which are more philosophic than specific, but i don't beg you for a reaction, it's just my add-on which might let you recycle your own thoughts and approve what looks right to you.

Thank you very much for your interest.

Claudius Raphael Paeth, A3lyphe
every breaking atom living ...
